# Generated by Django 5.2.7 on 2025-10-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gestion_calificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RemoveField(
            model_name='docente',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='docente',
            name='numero_empleado',
            field=models.CharField(default='temp_001', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='matricula',
            field=models.CharField(default='temp_001', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='docente',
            name='especialidad',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='fecha_inscripcion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
