# Generated by Django 5.2.7 on 2025-11-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_calificaciones', '0002_alter_usuario_options_remove_docente_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
