# Generated by Django 4.2.7 on 2025-12-04 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_calificaciones', '0003_usuario_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario del sistema'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='nombre',
            field=models.CharField(choices=[('espanol', 'Español'), ('matematicas', 'Matemáticas'), ('ingles', 'Inglés'), ('artes', 'Artes (Música)'), ('fisica', 'Física'), ('quimica', 'Química'), ('geografia', 'Geografía'), ('historia', 'Historia'), ('formacion_civica', 'Formación Cívica y Ética'), ('pecuaria', 'Pecuaria'), ('informatica', 'Informatica'), ('agritultura', 'Agritultura'), ('educacion_fisica', 'Educación Física')], max_length=100),
        ),
    ]
